#!/bin/bash
#


usage() {
    echo $"Usage: $0 {build/demo}"
    exit 1
}

case "$1" in
    build)
		docker-compose build
        ;;
    demo)
		# Since there was no service, we brings up the container with bash
		docker-compose run demo bash
        ;;
	logs)
		docker-compose logs
		;;
    *)  
        usage
        ;;
esac

