language: java

#Container-based
dist: trusty
sudo: false

matrix:
  include:
    # 8
    - env: JDK='Oracle JDK 8'
      jdk: oraclejdk8
    - env: JDK='OpenJDK 8'
      jdk: openjdk8

    # 9
    - env: JDK='Oracle JDK 9'
      jdk: oraclejdk9

script:
  - echo PATH = ${PATH}
  - echo JAVA_HOME = ${JAVA_HOME}
  - java -version
  - javac -version
  - ./travis.sh