/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_mcfongtw_jni_utils_MallocArenaUtils */

#ifndef _Included_com_github_mcfongtw_jni_utils_MallocArenaUtils
#define _Included_com_github_mcfongtw_jni_utils_MallocArenaUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_mcfongtw_jni_utils_MallocArenaUtils
 * Method:    mallocStats
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_mcfongtw_jni_utils_MallocArenaUtils_mallocStats
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
