/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_mcfongtw_jni_utils_MallocUtils */

#ifndef _Included_com_github_mcfongtw_jni_utils_MallocUtils
#define _Included_com_github_mcfongtw_jni_utils_MallocUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_mcfongtw_jni_utils_MallocUtils
 * Method:    mallocStats
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_mcfongtw_jni_utils_MallocUtils_mallocStats
  (JNIEnv *, jclass);

/*
 * Class:     com_github_mcfongtw_jni_utils_MallocUtils
 * Method:    mallopt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_github_mcfongtw_jni_utils_MallocUtils_mallopt
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_mcfongtw_jni_utils_MallocUtils
 * Method:    mtrace
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_mcfongtw_jni_utils_MallocUtils_mtrace
  (JNIEnv *, jclass);

/*
 * Class:     com_github_mcfongtw_jni_utils_MallocUtils
 * Method:    muntrace
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_mcfongtw_jni_utils_MallocUtils_muntrace
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_mcfongtw_jni_utils_MallocUtils_MallOpt */

#ifndef _Included_com_github_mcfongtw_jni_utils_MallocUtils_MallOpt
#define _Included_com_github_mcfongtw_jni_utils_MallocUtils_MallOpt
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
